name: Run cron projects

on:
  schedule:
    - cron: "0 3 * * SAT" # Run every sat

jobs:
  Run-Scheduled-Exports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: "3.11"

      - name: Shoot weekly projects
        run: python osm2hdx_extractor --fetch-scheduled-exports weekly
